### ISSUE TITLE
Why is the solution a function?

### ISSUE THREAD

**Issue by BlueTrin** [salt-die/aoc_lube#3]
Hi, I noticed that to submit, you need to pass an argument less callable.

Why is that?

I would have expected to pass either the solution or a function that takes the input as argument?

**Comment by salt-die** [comment]
This is so the submit function can be lazy; It will not call the passed function if a correct solution has already been submitted. So after I finish part 2, say, and part 1 has already been submitted, the line that submits part 1 will just immediately return so that part 2 can be submitted faster. This really only matters for solutions that take a while to compute, of course.

**Comment by BlueTrin** [comment]
Thanks vm it makes sense
